version: "3"
services:
  poc-kafka-app-container:
    restart: always
    image: poc-kafka-app:1
    container_name: 'poc-kafka-app'
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
    - /data/poc-kafka-app
    ports:
    - '9000:9000'
    depends_on:
      - kafka
      - zookeeper

  zookeeper:
    image: 'docker.io/bitnami/zookeeper:latest'
    container_name: 'zookeeper'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
      image: 'docker.io/bitnami/kafka:latest'
      container_name: 'kafka'
      ports:
        - '9092:9092'
        - '9093:9093'
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
        - KAFKA_CFG_ADVERTISED_HOST_NAME=kafka
        - KAFKA_CFG_ADVERTISED_PORT=9092
        - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://0.0.0.0:9093
        - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9093
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      depends_on:
        - zookeeper
